### ISSUE TITLE
Skip empty fields

### ISSUE THREAD

**Issue by parichit13** [stevetarver/excel-as-json#9]
Is it possible to skip some empty array fields in the excel. I have a use case where I may have multiple array objects for some rows and not for some like

packages[0].name     packages[1].name     packages[2].name
Discount                    Discount                    Offer
Discount                    Discount

when I try to parse such an excel, for the second row it gives me packages[2].name: 0 in the resulting json. Can you maybe add such a feature to skip empty fields ?

**Comment by stevetarver** [comment]
This is actually a bug in my code, thanks for pointing it out. All excel values are returned as string and I was using isFinite() to tell if that string was a number. isFinite() returns true for blank or empty strings.

I have just published version 1.0.4 which should resolve this issue.

**Comment by parichit13** [comment]
Thanks steve,
Even I was just about to tell you that I fixed that bug in your code today only. I forked your repository and I found a simple if condition to do that.

**Comment by stevetarver** [comment]
Thanks for going to the effort of debugging - it is rare and appreciated. Glad I could provide a solution. Hope this package makes something in your life easier.

**Comment by parichit13** [comment]
Hey steve,

The issue of skipping empty fields is still persisting. Can you fix this
issue soon.

Regards

Parichit Kotawala



 Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=parichit.kumark@gmail.com&idSignature=22>
